CREATE TABLE CARD(
ID_CARD NUMBER(6,0) CONSTRAINT PK_CARD PRIMARY KEY,
TIP_CARD VARCHAR2(50),
PIN CHAR(4),
DATA_EXPIRARII DATE,
ID_CL NUMBER(6,0)
);

ALTER TABLE CARD   --PINUL TREBUIE SA FIE DE 4 CIFRE
ADD CONSTRAINT VERIFICA_PIN
CHECK (LENGTH(PIN) = 4);

/*ALTER TABLE CARD   --DATA EXPIRARII CARDULUI NU POATE SA FIE MAI MICA DECAT DATA ACTUALA, ALTFEL CARDUL ESTE EXPIRAT
ADD CONSTRAINT VERIFICARE_DATA_EXPIRARII
CHECK (DATA_EXPIRARII > SYSDATE);*/ 

CREATE TABLE CLIENT(
ID_CL NUMBER(6,0) CONSTRAINT PK_ID_CL PRIMARY KEY,
NUME_CL VARCHAR2(50),
PRENUME_CL VARCHAR(50),
DATA_NASTERII_CL DATE,
ADRESA_CL VARCHAR(100),
EMAIL_CL VARCHAR2(50),
NR_TELEFON_CL CHAR(10)
);


ALTER TABLE CARD   --ID_CL CHEIE STRAINA IN TABELA CARD DIN TABELA CLIENT
ADD CONSTRAINT FK_ID_CL FOREIGN KEY (ID_CL)
REFERENCES CLIENT(ID_CL);

/*ALTER TABLE CLIENT
ADD CONSTRAINT VERIFICARE_VARSTA_CL
CHECK ((EXTRACT(YEAR FROM DATA_NASTERII_CL) - EXTRACT(YEAR FROM SYSDATE)) >= 18 );*/

ALTER TABLE CLIENT
ADD CONSTRAINT VERIFICARE_EMAIL_CL
CHECK (EMAIL_CL LIKE '%@%com');


ALTER TABLE CLIENT
ADD CONSTRAINT VERIFICARE_NR_TELEFON_CL
CHECK (LENGTH(NR_TELEFON_CL) =  10);

CREATE TABLE SOLD(
ID_SOLD NUMBER(6,0),
ID_CARD NUMBER(6,0),
SOLD NUMBER (12,2),
MONEDA VARCHAR2(10),
DATA_INTEROGARII_SOLDULUI DATE
);

ALTER TABLE SOLD 
ADD CONSTRAINT PK_ID_SOLD PRIMARY KEY (ID_SOLD);


ALTER TABLE SOLD
ADD CONSTRAINT FK_ID_CARD FOREIGN KEY (ID_CARD)
REFERENCES CARD(ID_CARD);

CREATE TABLE DEPUNERE(
ID_DEPUNERE NUMBER(6,0) CONSTRAINT PK_ID_DEPUNERE PRIMARY KEY,
ID_CARD NUMBER(6,0),
MONEDA_DEPUNERE VARCHAR2(10),
SUMA_DEP NUMBER(10,2),
MOTIV VARCHAR2(100)
);


ALTER TABLE DEPUNERE
ADD CONSTRAINT FK_ID_CARD_DEP FOREIGN KEY (ID_CARD)
REFERENCES CARD(ID_CARD);

CREATE TABLE RETRAGERE(
ID_RETRAGERE NUMBER(6,0) CONSTRAINT PK_ID_RETRAGERE PRIMARY KEY,
ID_CARD NUMBER(6,0),
SUMA NUMBER(12,2)
);

ALTER TABLE RETRAGERE
ADD CONSTRAINT FK_ID_CARD_RET FOREIGN KEY (ID_CARD)
REFERENCES CARD(ID_CARD);

/*ALTER TABLE RETRAGERE     --SUMA RETRASA NU POATE FI MAI MARE DECAT SOLDUL ACTUAL AFERENT CARDULUI
ADD CONSTRAINT VERIFICARE_SUMA_RETRASA 
CHECK ((SELECT SOLD
       FROM SOLD S, CARD C, RETRAGERE R
       WHERE S.ID_CARD = C.ID_CARD AND R.ID_CARD = C.ID_CARD) >= SUMA);*/

CREATE TABLE TIPUL_TRANZACTIEI(
ID_TIP NUMBER(6,0) CONSTRAINT PK_ID_TIP PRIMARY KEY,
TIPUL VARCHAR2(50)
);

ALTER TABLE TIPUL_TRANZACTIEI
ADD CONSTRAINT VERIFICARE_TIP_TRANZACTIE
CHECK (LOWER(TIPUL) IN ('interogare sold', 'retragere', 'depunere'));

CREATE TABLE INREGISTRARE_TRANZACTIE(
ID_TRANZACTIE NUMBER(6,0) CONSTRAINT PK_ID_TRANZACTIE PRIMARY KEY,
ID_TIP NUMBER(6,0),
ID_CL NUMBER(6,0),
ID_CARD NUMBER(6,0),
DATA_INREG DATE
);

ALTER TABLE INREGISTRARE_TRANZACTIE
ADD CONSTRAINT FK_ID_CARD_TRANZ FOREIGN KEY (ID_CARD)
REFERENCES CARD(ID_CARD);

ALTER TABLE INREGISTRARE_TRANZACTIE
ADD CONSTRAINT FK_ID_TIP_TRANZ FOREIGN KEY (ID_TIP)
REFERENCES TIPUL_TRANZACTIEI(ID_TIP);

ALTER TABLE INREGISTRARE_TRANZACTIE
ADD CONSTRAINT FK_ID_CL_TRANZ FOREIGN KEY (ID_CL)
REFERENCES CLIENT(ID_CL);

COMMIT;
